name: "S3 Sync"
description: "Sync a directory to an AWS S3 repository"
author: jakejarvis
inputs:
  args:
    description: 'Additional arguments for s3 sync'
    required: false
outputs:
  stringtag:
    description: 'A static string to confirm this action was run'
    value: 'The sync action completed running'
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.args }}
branding:
  icon: refresh-cw
  color: green
